# Generated by Django 5.2 on 2025-04-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_imagefile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageprediction",
            name="image",
        ),
        migrations.DeleteModel(
            name="ImageFile",
        ),
    ]
