# Generated by Django 5.2 on 2025-04-30 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_remove_imageprediction_image_delete_imagefile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="project.imageprediction",
                    ),
                ),
            ],
        ),
    ]
